import { WorkspaceSnapshot } from '../../workspace/types';

// Inlined desktop snapshot data (previously from desktop-snapshot.json)
const DESKTOP_SNAPSHOT: WorkspaceSnapshot = {
  id: 'adaptive-desktop-snapshot',
  name: 'Adaptive Desktop Snapshot Example',
  workspaceContexts: [
    {
      id: 'ultrawide',
      name: 'Ultrawide Monitor',
      minimumViewportScreenHeight: 300,
      minimumViewportScreenWidth: 300,
      aspectRatio: 2.333,
      deviceType: 'ultrawide',
      maxScreenBounds: { x: 0, y: 0, width: 3440, height: 1440 },
      orientation: 'landscape',
      sizeCategory: 'lg',
      viewportSnapshots: [
        {
          id: 'main',
          bounds: { x: 0, y: 0, width: 0.75, height: 1 },
          isDefault: false,
          isMaximized: false,
          isMinimized: false,
          isRequired: true,
          timestamp: 1639547653210,
        },
        {
          id: 'side',
          bounds: { x: 0.75, y: 0, width: 0.25, height: 1 },
          isDefault: false,
          isMaximized: false,
          isMinimized: false,
          isRequired: false,
          timestamp: 1639547653211,
        },
      ],
    },
    {
      id: 'laptop',
      name: 'Laptop Display',
      minimumViewportScreenHeight: 300,
      minimumViewportScreenWidth: 300,
      aspectRatio: 1.6,
      sizeCategory: 'md',
      deviceType: 'standard-laptop',
      maxScreenBounds: { x: 0, y: 0, width: 1440, height: 900 },
      orientation: 'landscape',
      viewportSnapshots: [
        {
          id: 'main',
          bounds: { x: 0, y: 0, width: 0.75, height: 1 },
          isDefault: true,
          isMaximized: false,
          isMinimized: false,
          isRequired: true,
          timestamp: 1639547653212,
        },
        {
          id: 'side',
          bounds: { x: 0.75, y: 0, width: 0.25, height: 1 },
          isDefault: false,
          isMaximized: false,
          isMinimized: true,
          isRequired: false,
          timestamp: 1639547653213,
        },
      ],
    },
    {
      id: 'tablet-landscape',
      name: 'Landscape Tablet Display',
      minimumViewportScreenHeight: 300,
      minimumViewportScreenWidth: 300,
      aspectRatio: 1.6,
      sizeCategory: 'sm',
      deviceType: 'small-tablet',
      maxScreenBounds: { x: 0, y: 0, width: 1024, height: 768 },
      orientation: 'landscape',
      viewportSnapshots: [
        {
          id: 'main',
          bounds: { x: 0, y: 0, width: 0.75, height: 1 },
          isDefault: true,
          isMaximized: false,
          isMinimized: false,
          isRequired: true,
          timestamp: 1639547653212,
        },
        {
          id: 'side',
          bounds: { x: 0.75, y: 0, width: 0.25, height: 1 },
          isDefault: false,
          isMaximized: false,
          isMinimized: true,
          isRequired: false,
          timestamp: 1639547653213,
        },
      ],
    },
    {
      id: 'tablet-portrait',
      name: 'Portrait Laptop Display',
      minimumViewportScreenHeight: 300,
      minimumViewportScreenWidth: 300,
      aspectRatio: 1.6,
      sizeCategory: 'sm',
      deviceType: 'small-tablet',
      maxScreenBounds: { x: 0, y: 0, width: 768, height: 1024 },
      orientation: 'portrait',
      viewportSnapshots: [
        {
          id: 'main',
          bounds: { x: 0, y: 0, width: 0.5, height: 1 },
          isDefault: true,
          isMaximized: false,
          isMinimized: false,
          isRequired: true,
          timestamp: 1639547653212,
        },
        {
          id: 'side',
          bounds: { x: 0.5, y: 0, width: 0.5, height: 1 },
          isDefault: false,
          isMaximized: false,
          isMinimized: true,
          isRequired: false,
          timestamp: 1639547653213,
        },
      ],
    },
    {
      id: 'phone',
      name: 'Phone Portrait',
      minimumViewportScreenHeight: 300,
      minimumViewportScreenWidth: 300,
      aspectRatio: 0.4615,
      sizeCategory: 'sm',
      deviceType: 'phone',
      maxScreenBounds: { x: 0, y: 0, width: 375, height: 812 },
      orientation: 'portrait',
      viewportSnapshots: [
        {
          id: 'main',
          bounds: { x: 0, y: 0, width: 1, height: 0.5 },
          isDefault: true,
          isMaximized: false,
          isMinimized: false,
          isRequired: true,
          timestamp: 1639547653214,
        },
        {
          id: 'side',
          bounds: { x: 0, y: 0.5, width: 1, height: 0.5 },
          isDefault: false,
          isMaximized: false,
          isMinimized: true,
          isRequired: false,
          timestamp: 1639547653215,
        },
      ],
    },
  ],
};

export function loadDesktopSnapshot(): WorkspaceSnapshot {
  return DESKTOP_SNAPSHOT;
}
